local ThreadTitle = require("avante.thread_title")

describe("thread title", function()
  describe("color_index", function()
    it("cycles numbered threads through the palette", function()
      assert.equals(1, ThreadTitle.color_index("1.json", 3))
      assert.equals(2, ThreadTitle.color_index("2.json", 3))
      assert.equals(3, ThreadTitle.color_index("3.json", 3))
      assert.equals(1, ThreadTitle.color_index("4.json", 3))
    end)

    it("falls back to the first color for invalid input", function()
      assert.equals(1, ThreadTitle.color_index(nil, 6))
      assert.equals(1, ThreadTitle.color_index("external.json", 6))
      assert.equals(1, ThreadTitle.color_index("2.json", 0))
    end)
  end)

  describe("display", function()
    it("uses an explicit thread title", function()
      assert.equals("Investigate auth", ThreadTitle.display({ title = " Investigate auth ", filename = "3.json" }))
    end)

    it("gives untitled threads an identifiable fallback", function()
      assert.equals("Untitled #3", ThreadTitle.display({ title = "untitled", filename = "3.json" }))
      assert.equals("Untitled", ThreadTitle.display(nil))
    end)
  end)
end)
