-- Run from the repository root: nvim --headless -u NONE -l scripts/check-template-include.lua
package.cpath = "./lua/?.so;" .. package.cpath
local templates = require("avante_templates")
local dir = vim.fn.tempname()
local cwd = vim.fn.getcwd()
vim.fn.mkdir(dir .. "/templates", "p")
vim.fn.mkdir(dir .. "/project", "p")
vim.fn.writefile({ "outside cwd" }, dir .. "/foreign.jinja", "b")
vim.fn.writefile({ '{% include "linked.jinja" %}' }, dir .. "/templates/main.jinja", "b")
local ok, result = pcall(function()
  assert(vim.uv.fs_symlink(dir .. "/foreign.jinja", dir .. "/project/linked.jinja"))
  vim.api.nvim_set_current_dir(dir .. "/project")
  templates.initialize(dir .. "/templates", vim.fn.getcwd())
  return templates.render("main.jinja", { ask = true, code_lang = "lua" })
end)
vim.api.nvim_set_current_dir(cwd)
vim.fn.delete(dir, "rf")
assert(ok, result)
assert(result == "outside cwd", result)
print("PASS: included a file outside cwd and both template roots through a symlink in cwd")
